// Generated by using Rcpp::compileAttributes() -> do not edit by hand
// Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

#include <RcppArmadillo.h>
#include <Rcpp.h>

using namespace Rcpp;

#ifdef RCPP_USE_GLOBAL_ROSTREAM
Rcpp::Rostream<true>&  Rcpp::Rcout = Rcpp::Rcpp_cout_get();
Rcpp::Rostream<false>& Rcpp::Rcerr = Rcpp::Rcpp_cerr_get();
#endif

// nearestScore
arma::mat nearestScore(arma::mat ctr_score, arma::mat trt_score);
RcppExport SEXP _blazingMatch_nearestScore(SEXP ctr_scoreSEXP, SEXP trt_scoreSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< arma::mat >::type ctr_score(ctr_scoreSEXP);
    Rcpp::traits::input_parameter< arma::mat >::type trt_score(trt_scoreSEXP);
    rcpp_result_gen = Rcpp::wrap(nearestScore(ctr_score, trt_score));
    return rcpp_result_gen;
END_RCPP
}

static const R_CallMethodDef CallEntries[] = {
    {"_blazingMatch_nearestScore", (DL_FUNC) &_blazingMatch_nearestScore, 2},
    {NULL, NULL, 0}
};

RcppExport void R_init_blazingMatch(DllInfo *dll) {
    R_registerRoutines(dll, NULL, CallEntries, NULL, NULL);
    R_useDynamicSymbols(dll, FALSE);
}
