# Generated by using Rcpp::compileAttributes() -> do not edit by hand
# Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

#' nearest score search c++ implementation.
#'
#' @param ctr_score matrix containing control group index and score
#' @param trt_score matrix containing treatment group index and score
#' @return matched treatment and control indices
#' @examples
#'
#' trt_score = data.frame(index=c(1:5), score=c(0.1, 0.03, 0.7, 0.2, 0.5))
#' ctr_score = data.frame(index=c(1:20), score=runif(20))
#' trt_score = trt_score[order(trt_score$score), ]
#' ctr_score = ctr_score[order(ctr_score$score), ]
#' nearestScore(as.matrix(ctr_score), as.matrix(trt_score))
#'
#' @export
nearestScore <- function(ctr_score, trt_score) {
    .Call('_blazingMatch_nearestScore', PACKAGE = 'blazingMatch', ctr_score, trt_score)
}

